### ISSUE TITLE
Fully loading redscreen on post-mission screws up dropship interior

### ISSUE THREAD

**Issue by Xymanek** [shiremct/WOTC_LW2Secondaries#2]
![image](https://user-images.githubusercontent.com/2865341/57012676-6584f680-6c10-11e9-87ca-0b62cd60b00d.png)

And this is what happens if you try to exit the redscreen:

![image](https://user-images.githubusercontent.com/2865341/57012689-6d449b00-6c10-11e9-9069-8b5884a2b9ac.png)

I know the UI interaction isn't a fault of this mod, but would be nice if this redscreen could be fixed

**Comment by Iridar** [comment]
Since [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=1736342239) now exists to prevent this issue, and since this issue is not specific to this mod, a lot of mods use the same CHL method for adding sockets, this issue can be closed, in my opinion.
